openapi: 3.1.0
info:
  title: Price-Sentiment Overlay API
  description: API endpoints for OHLC price data and sentiment history
  version: 1.0.0
  contact:
    name: Sentiment Analyzer Team

servers:
  - url: https://ee2a3fxtkxmpwp2bhul3uylmb40hfknf.lambda-url.us-east-1.on.aws
    description: Preprod environment
  - url: https://prod-sentiment-dashboard.lambda-url.us-east-1.on.aws
    description: Production environment

paths:
  /api/v2/tickers/{ticker}/ohlc:
    get:
      operationId: getOHLCData
      summary: Get OHLC price data for a ticker
      description: |
        Returns historical OHLC (Open, High, Low, Close) candlestick data for the specified ticker.
        Data is cached until the next market open to minimize external API calls.
      tags:
        - Price Data
      parameters:
        - name: ticker
          in: path
          required: true
          description: Stock ticker symbol (e.g., AAPL, MSFT)
          schema:
            type: string
            pattern: '^[A-Z]{1,5}$'
            example: AAPL
        - name: range
          in: query
          required: false
          description: Predefined time range for data
          schema:
            type: string
            enum: [1W, 1M, 3M, 6M, 1Y]
            default: 1M
        - name: start_date
          in: query
          required: false
          description: Custom start date (overrides range if provided)
          schema:
            type: string
            format: date
            example: "2024-01-01"
        - name: end_date
          in: query
          required: false
          description: Custom end date (defaults to today)
          schema:
            type: string
            format: date
            example: "2024-12-01"
      security:
        - UserIdHeader: []
      responses:
        '200':
          description: OHLC data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OHLCResponse'
        '400':
          description: Invalid ticker symbol or date range
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Missing or invalid user identification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Ticker not found or no data available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: External data source unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v2/tickers/{ticker}/sentiment/history:
    get:
      operationId: getSentimentHistory
      summary: Get historical sentiment data for a ticker
      description: |
        Returns historical sentiment scores for the specified ticker and source.
        Sentiment is available for all calendar days (including weekends).
      tags:
        - Sentiment Data
      parameters:
        - name: ticker
          in: path
          required: true
          description: Stock ticker symbol
          schema:
            type: string
            pattern: '^[A-Z]{1,5}$'
            example: AAPL
        - name: source
          in: query
          required: false
          description: Sentiment source to retrieve
          schema:
            type: string
            enum: [tiingo, finnhub, our_model, aggregated]
            default: aggregated
        - name: range
          in: query
          required: false
          description: Predefined time range
          schema:
            type: string
            enum: [1W, 1M, 3M, 6M, 1Y]
            default: 1M
        - name: start_date
          in: query
          required: false
          description: Custom start date
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: false
          description: Custom end date
          schema:
            type: string
            format: date
      security:
        - UserIdHeader: []
      responses:
        '200':
          description: Sentiment history retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SentimentHistoryResponse'
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Missing or invalid user identification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Ticker not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    UserIdHeader:
      type: apiKey
      in: header
      name: X-User-ID
      description: User ID from anonymous session authentication

  schemas:
    PriceCandle:
      type: object
      required:
        - date
        - open
        - high
        - low
        - close
      properties:
        date:
          type: string
          format: date
          description: Trading day date
          example: "2024-11-29"
        open:
          type: number
          format: float
          description: Opening price
          example: 237.45
        high:
          type: number
          format: float
          description: Highest price
          example: 239.12
        low:
          type: number
          format: float
          description: Lowest price
          example: 236.80
        close:
          type: number
          format: float
          description: Closing price
          example: 238.67
        volume:
          type: integer
          nullable: true
          description: Trading volume
          example: 45678900

    OHLCResponse:
      type: object
      required:
        - ticker
        - candles
        - time_range
        - start_date
        - end_date
        - count
        - source
        - cache_expires_at
      properties:
        ticker:
          type: string
          description: Stock symbol
          example: AAPL
        candles:
          type: array
          items:
            $ref: '#/components/schemas/PriceCandle'
          description: Array of OHLC candles, oldest first
        time_range:
          type: string
          enum: [1W, 1M, 3M, 6M, 1Y, custom]
          description: Time range used
          example: 1M
        start_date:
          type: string
          format: date
          description: First candle date
          example: "2024-11-01"
        end_date:
          type: string
          format: date
          description: Last candle date
          example: "2024-11-29"
        count:
          type: integer
          description: Number of candles returned
          example: 21
        source:
          type: string
          enum: [tiingo, finnhub]
          description: Data source used
          example: tiingo
        cache_expires_at:
          type: string
          format: date-time
          description: When cached data expires (next market open)
          example: "2024-12-02T14:30:00Z"

    SentimentPoint:
      type: object
      required:
        - date
        - score
        - source
      properties:
        date:
          type: string
          format: date
          description: Date of sentiment measurement
          example: "2024-11-29"
        score:
          type: number
          format: float
          minimum: -1.0
          maximum: 1.0
          description: Sentiment score
          example: 0.65
        source:
          type: string
          enum: [tiingo, finnhub, our_model, aggregated]
          description: Sentiment source
          example: aggregated
        confidence:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          nullable: true
          description: Model confidence
          example: 0.85
        label:
          type: string
          enum: [positive, neutral, negative]
          nullable: true
          description: Sentiment classification
          example: positive

    SentimentHistoryResponse:
      type: object
      required:
        - ticker
        - source
        - history
        - start_date
        - end_date
        - count
      properties:
        ticker:
          type: string
          example: AAPL
        source:
          type: string
          enum: [tiingo, finnhub, our_model, aggregated]
          example: aggregated
        history:
          type: array
          items:
            $ref: '#/components/schemas/SentimentPoint'
        start_date:
          type: string
          format: date
          example: "2024-11-01"
        end_date:
          type: string
          format: date
          example: "2024-11-29"
        count:
          type: integer
          example: 29

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: INVALID_TICKER
        message:
          type: string
          description: Human-readable error message
          example: "Ticker symbol 'INVALID' not found"
        details:
          type: object
          nullable: true
          description: Additional error details
