openapi: 3.0.3
info:
  title: OHLC Resolution Selector API
  description: API contract for OHLC candlestick data with resolution selection
  version: 1.0.0

paths:
  /api/v2/tickers/{ticker}/ohlc:
    get:
      summary: Get OHLC candlestick data
      description: |
        Returns OHLC (Open, High, Low, Close) candlestick data for a ticker
        at the specified resolution. Supports intraday (1m, 5m, 15m, 30m, 1h)
        and daily resolutions.
      operationId: getOHLC
      parameters:
        - name: ticker
          in: path
          required: true
          description: Stock ticker symbol (1-5 uppercase letters)
          schema:
            type: string
            pattern: "^[A-Z]{1,5}$"
            example: "AAPL"
        - name: range
          in: query
          required: false
          description: Time range for data. Ignored if start_date/end_date provided.
          schema:
            type: string
            enum: ["1W", "1M", "3M", "6M", "1Y"]
            default: "1M"
        - name: resolution
          in: query
          required: false
          description: |
            Candlestick time resolution. Auto-limits time range based on resolution:
            - "1": 1 minute (max 7 days)
            - "5": 5 minutes (max 30 days)
            - "15": 15 minutes (max 90 days)
            - "30": 30 minutes (max 90 days)
            - "60": 1 hour (max 180 days)
            - "D": Daily (max 365 days)
          schema:
            type: string
            enum: ["1", "5", "15", "30", "60", "D"]
            default: "D"
        - name: start_date
          in: query
          required: false
          description: Custom start date (ISO 8601 format, overrides range)
          schema:
            type: string
            format: date
            example: "2024-01-15"
        - name: end_date
          in: query
          required: false
          description: Custom end date (ISO 8601 format)
          schema:
            type: string
            format: date
            example: "2024-01-22"
      responses:
        "200":
          description: Successful response with OHLC data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OHLCResponse"
        "400":
          description: Invalid parameters (bad ticker format, invalid resolution)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Ticker not found or no data available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "502":
          description: Data provider error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    OHLCResponse:
      type: object
      required:
        - ticker
        - candles
        - time_range
        - start_date
        - end_date
        - count
        - source
        - resolution
      properties:
        ticker:
          type: string
          description: Stock ticker symbol
          example: "AAPL"
        candles:
          type: array
          items:
            $ref: "#/components/schemas/PriceCandle"
        time_range:
          type: string
          description: Time range used for query
          example: "1M"
        start_date:
          type: string
          format: date
          description: Start date of returned data
          example: "2024-01-15"
        end_date:
          type: string
          format: date
          description: End date of returned data
          example: "2024-01-22"
        count:
          type: integer
          description: Number of candles returned
          example: 100
        source:
          type: string
          description: Data source used (finnhub or tiingo)
          enum: ["finnhub", "tiingo"]
          example: "finnhub"
        resolution:
          type: string
          description: Resolution of returned candles
          enum: ["1", "5", "15", "30", "60", "D"]
          example: "5"
        cache_expires_at:
          type: string
          format: date-time
          description: Cache expiration timestamp
          example: "2024-01-22T15:30:00Z"
        resolution_fallback:
          type: boolean
          description: True if requested resolution was unavailable and fell back
          example: false
        fallback_message:
          type: string
          description: Explanation if fallback occurred
          example: "Intraday data unavailable for AAPL, showing daily"

    PriceCandle:
      type: object
      required:
        - date
        - open
        - high
        - low
        - close
      properties:
        date:
          type: string
          format: date-time
          description: Candle timestamp (bucket start time)
          example: "2024-01-22T14:30:00Z"
        open:
          type: number
          format: double
          description: Opening price
          example: 150.25
        high:
          type: number
          format: double
          description: Highest price
          example: 151.00
        low:
          type: number
          format: double
          description: Lowest price
          example: 149.50
        close:
          type: number
          format: double
          description: Closing price
          example: 150.75
        volume:
          type: integer
          description: Trading volume (optional)
          example: 1234567

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INVALID_RESOLUTION"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid resolution '2m'. Supported values: 1, 5, 15, 30, 60, D"
        details:
          type: object
          description: Additional error context
          additionalProperties: true
