# Stripe Webhook Endpoint Contract
# POST /webhooks/stripe

openapi: 3.0.3
info:
  title: Stripe Webhook API
  version: 1.0.0

paths:
  /webhooks/stripe:
    post:
      summary: Handle Stripe webhook events
      description: |
        Receives Stripe webhook events for subscription lifecycle.
        Signature verified via stripe-signature header.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripeEvent'
      parameters:
        - name: stripe-signature
          in: header
          required: true
          schema:
            type: string
          description: HMAC-SHA256 signature for verification
      responses:
        '200':
          description: Event processed or already processed (idempotent)
        '400':
          description: Invalid signature or malformed event
        '500':
          description: Processing error (Stripe will retry)

components:
  schemas:
    StripeEvent:
      type: object
      required:
        - id
        - type
        - data
      properties:
        id:
          type: string
          description: Unique event ID (used for idempotency)
          example: evt_1NqIXX2eZvKYlo2C
        type:
          type: string
          enum:
            - customer.subscription.created
            - customer.subscription.updated
            - customer.subscription.deleted
          description: Event type
        data:
          type: object
          properties:
            object:
              $ref: '#/components/schemas/Subscription'

    Subscription:
      type: object
      properties:
        id:
          type: string
          example: sub_1NqIXX2eZvKYlo2C
        customer:
          type: string
          description: Stripe customer ID (maps to user_id via metadata)
        status:
          type: string
          enum: [active, canceled, past_due, unpaid]
        metadata:
          type: object
          properties:
            user_id:
              type: string
              description: Our internal user ID
        items:
          type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  price:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Price ID (maps to role)
