# Email-to-OAuth Link API Contract
# Feature: 1182-email-to-oauth-link
# Date: 2026-01-09

openapi: 3.0.3
info:
  title: Email-to-OAuth Link API
  version: 1.0.0
  description: API endpoints for Flow 4 - linking email to OAuth accounts

paths:
  /v2/auth/link-email:
    post:
      summary: Initiate email linking
      description: |
        Start the email linking process for an OAuth-authenticated user.
        Stores pending_email on user record and sends magic link.
      operationId: linkEmailToOAuthUser
      tags:
        - Authentication
      security:
        - sessionCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: Email address to link to account
                  example: user@example.com
      responses:
        '202':
          description: Magic link sent to email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Verification email sent
        '400':
          description: Invalid request or email already linked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v2/auth/complete-email-link:
    post:
      summary: Complete email linking
      description: |
        Complete the email linking process by verifying magic link token.
        Adds email to linked_providers and clears pending_email.
      operationId: completeEmailLink
      tags:
        - Authentication
      security:
        - sessionCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Magic link token from email
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      responses:
        '200':
          description: Email successfully linked
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email linked successfully
                  linked_providers:
                    type: array
                    items:
                      type: string
                    example: ["google", "email"]
        '400':
          description: Invalid, expired, or already used token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated or token user mismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: session_id
      description: Session cookie from OAuth authentication

  schemas:
    ErrorResponse:
      type: object
      required:
        - error_code
        - message
      properties:
        error_code:
          type: string
          description: Machine-readable error code
          example: AUTH_010
        message:
          type: string
          description: Human-readable error message
          example: Magic link is invalid or expired
