openapi: 3.0.3
info:
  title: Ingestion Collision Metrics API
  description: API for querying cross-source deduplication metrics
  version: 1.0.0

paths:
  /api/v2/metrics/ingestion:
    get:
      summary: Get ingestion metrics
      description: Returns collision metrics for the specified time range
      operationId: getIngestionMetrics
      parameters:
        - name: start_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Start of time range (ISO8601). Defaults to 24h ago.
        - name: end_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: End of time range (ISO8601). Defaults to now.
        - name: source
          in: query
          required: false
          schema:
            type: string
            enum: [tiingo, finnhub, all]
            default: all
          description: Filter by source
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionMetricsResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/v2/metrics/attribution:
    get:
      summary: Get source attribution summary
      description: Returns aggregated attribution statistics showing which sources contribute articles
      operationId: getAttributionSummary
      parameters:
        - name: start_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Start of time range (ISO8601). Defaults to 24h ago.
        - name: end_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: End of time range (ISO8601). Defaults to now.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttributionSummaryResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/v2/metrics/collisions:
    get:
      summary: Get collision statistics
      description: Returns detailed collision statistics for cross-source deduplication
      operationId: getCollisionStats
      parameters:
        - name: start_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: end_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: ticker
          in: query
          required: false
          schema:
            type: string
          description: Filter by ticker symbol
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollisionStatsResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    IngestionMetricsResponse:
      type: object
      required:
        - time_range
        - totals
        - by_source
      properties:
        time_range:
          type: object
          properties:
            start: { type: string, format: date-time }
            end: { type: string, format: date-time }
        totals:
          type: object
          properties:
            articles_fetched: { type: integer }
            articles_stored: { type: integer }
            collisions_detected: { type: integer }
            collision_rate: { type: number, format: float }
        by_source:
          type: object
          additionalProperties:
            type: object
            properties:
              articles_fetched: { type: integer }
              articles_contributed: { type: integer }
              unique_only: { type: integer }

    AttributionSummaryResponse:
      type: object
      required:
        - time_range
        - total_articles
        - by_source
        - by_wire_service
      properties:
        time_range:
          type: object
          properties:
            start: { type: string, format: date-time }
            end: { type: string, format: date-time }
        total_articles:
          type: integer
          description: Total unique articles in time range
        by_source:
          type: object
          description: Breakdown by API source (tiingo, finnhub)
          additionalProperties:
            type: object
            properties:
              articles_provided: { type: integer }
              exclusive_articles: { type: integer }
              shared_articles: { type: integer }
        by_wire_service:
          type: object
          description: Breakdown by wire service (reuters, ap, bloomberg, etc.)
          additionalProperties:
            type: object
            properties:
              count: { type: integer }
              sources: { type: array, items: { type: string } }

    CollisionStatsResponse:
      type: object
      required:
        - time_range
        - collision_rate
        - multi_source_articles
        - single_source_articles
      properties:
        time_range:
          type: object
          properties:
            start: { type: string, format: date-time }
            end: { type: string, format: date-time }
        collision_rate:
          type: number
          format: float
          description: Percentage of articles found in multiple sources (0.0-1.0)
        multi_source_articles:
          type: integer
          description: Count of articles found in 2+ sources
        single_source_articles:
          type: object
          properties:
            tiingo_only: { type: integer }
            finnhub_only: { type: integer }
        top_collisions:
          type: array
          description: Recent articles found in multiple sources
          items:
            type: object
            properties:
              headline: { type: string }
              sources:
                type: array
                items: { type: string }
              timestamp: { type: string, format: date-time }
              matched_tickers:
                type: array
                items: { type: string }

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []
