# Validation Error (422) Response Contract
# Must be byte-identical to FastAPI's automatic 422 format (FR-009, US3)

openapi: "3.1.0"
info:
  title: Validation Error Contract (FastAPI Parity)
  version: "2.0.0"

components:
  schemas:
    ValidationErrorResponse:
      type: object
      required: [detail]
      properties:
        detail:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"

    ValidationErrorDetail:
      type: object
      required: [loc, msg, type]
      properties:
        loc:
          type: array
          minItems: 1
          items:
            oneOf:
              - type: string
              - type: integer
          examples:
            - ["query", "resolution"]
            - ["body", "ticker"]
            - ["path", "config_id"]
            - ["body", "rules", 0, "threshold"]
        msg:
          type: string
          examples:
            - "Input should be 'D', 'W', 'M' or 'Y'"
            - "Field required"
            - "String should have at most 10 characters"
            - "Value error, invalid ticker format"
        type:
          type: string
          examples:
            - enum
            - missing
            - string_type
            - string_too_long
            - value_error

  examples:
    # Query parameter validation
    invalid_resolution:
      summary: Invalid enum value in query parameter
      value:
        detail:
          - loc: ["query", "resolution"]
            msg: "Input should be 'D', 'W', 'M' or 'Y'"
            type: enum

    # Multiple validation errors
    multiple_errors:
      summary: Multiple fields fail validation simultaneously
      value:
        detail:
          - loc: ["body", "ticker"]
            msg: "Field required"
            type: missing
          - loc: ["body", "threshold"]
            msg: "Input should be greater than 0"
            type: greater_than

    # Path parameter validation
    invalid_path_param:
      summary: Invalid path parameter format
      value:
        detail:
          - loc: ["path", "config_id"]
            msg: "String should match pattern '^cfg-[a-z0-9]+$'"
            type: string_pattern_mismatch

    # Nested body validation
    nested_body_error:
      summary: Error in nested body field
      value:
        detail:
          - loc: ["body", "rules", 0, "threshold"]
            msg: "Input should be less than or equal to 1.0"
            type: less_than_equal

    # Unknown range value
    unknown_range:
      summary: Unknown range value with valid options listed
      value:
        detail:
          - loc: ["query", "range"]
            msg: "Input should be '1D', '5D', '1M', '3M', '6M', '1Y', '5Y' or 'MAX'"
            type: enum

# Implementation contract:
# 1. Pydantic ValidationError.errors() produces this format natively
# 2. Location prefix mapping:
#    - event["queryStringParameters"] → ["query", field_name]
#    - event["pathParameters"] → ["path", field_name]
#    - event["body"] (parsed) → ["body", field_name, ...]
#    - event["headers"] → ["header", field_name]
# 3. Response HTTP status code: always 422
# 4. Content-Type: always application/json
# 5. Frontend parses: response.detail[0].loc, .msg, .type
